### ISSUE TITLE
add support

### ISSUE THREAD

**Issue by chacawaca** [palourde/homebridge-sinope#10]
Can you merge Onixx added support in your release?

thanks you

**Comment by Pblondin123** [comment]
> Can you merge Onixx added support in your release?
> 
> thanks you

the plugin owner does not seem to answer anymore :-(

**Comment by Pblondin123** [comment]
Am about to purchase a dimmer and i just realized the current version won't support :-(

**Comment by Pblondin123** [comment]
@palourde Simon:  great plugin i use it inside out every day.   Ta contribution serait appreciee !  MERCI d'avance!

**Comment by frobichaud** [comment]
@Pblondin123 I forked the repo and published the plugin homebridge-sinope-devices that contains Onixx changes. It should be as simple as disabling homebridge-sinope and installing homebridge-sinope-devices.

**Comment by Pblondin123** [comment]
Thanks @frobichaud .   I installed yours will have a look.   I have to admit i moved on to Hubitat as i was caught with the sinope plugin unmaintained.   I may come back!  Merci encore.

**Comment by Pblondin123** [comment]
Hi @frobichaud i had to uninstall your plugin as i had a UUID error i can't figure out what the issue is (had to disable the plugin).   I created a new issue wondering if you could take a look.  Thanks!

**Comment by frobichaud** [comment]
@Pblondin123 you have to remove the accessory linked to the homebridge-sinope plugin before you activate my homebridge-sinope-devices fork

1. Go to Homebridge settings
![Capture d’écran, le 2023-05-01 à 20 36 37](https://user-images.githubusercontent.com/3533748/235555330-54548ac5-384d-437b-9272-53d14e7095a8.png)

2. Select Remove Single Cached Accessory
![Capture d’écran, le 2023-05-01 à 20 35 28](https://user-images.githubusercontent.com/3533748/235555178-a053f6b8-6601-48d8-b060-2f2738d1eef0.png)

3. Find the accessory and delete it
![Capture d’écran, le 2023-05-01 à 20 37 10](https://user-images.githubusercontent.com/3533748/235555377-a0b099ec-65c5-498a-8d15-f0f7bffbd94b.png)

**Comment by Pblondin123** [comment]
Looks good merci!

**Comment by Pblondin123** [comment]
@frobichaud  - Actually this came back right after my next manual restart:  [5/2/2023, 5:39:48 p.m.] [homebridge-sinope-devices] Restoring existing accessory from cache: SP2600ZB
Error: Cannot add a Service with the same UUID '00000047-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Accessory.ts:552:17)
    at PlatformAccessory.addService (/usr/lib/node_modules/homebridge/src/platformAccessory.ts:98:41)
    at new SinopeOutletAccessory (/usr/lib/node_modules/homebridge-sinope-devices/src/platformAccessory.ts:407:35)
    at SinopePlatform.discoverDevices (/usr/lib/node_modules/homebridge-sinope-devices/src/platform.ts:217:11)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at HomebridgeAPI.<anonymous> (/usr/lib/node_modules/homebridge-sinope-devices/src/platform.ts:43:7)
